/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangCreateRouteImport } from './routes/$lang.create'
import { Route as LangArRouteImport } from './routes/$lang.ar'
import { Route as LangLessonIdRouteImport } from './routes/$lang.lesson.$id'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangCreateRoute = LangCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => LangRoute,
} as any)
const LangArRoute = LangArRouteImport.update({
  id: '/ar',
  path: '/ar',
  getParentRoute: () => LangRoute,
} as any)
const LangLessonIdRoute = LangLessonIdRouteImport.update({
  id: '/lesson/$id',
  path: '/lesson/$id',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/ar': typeof LangArRoute
  '/$lang/create': typeof LangCreateRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/lesson/$id': typeof LangLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/ar': typeof LangArRoute
  '/$lang/create': typeof LangCreateRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/lesson/$id': typeof LangLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/ar': typeof LangArRoute
  '/$lang/create': typeof LangCreateRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/lesson/$id': typeof LangLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/ar'
    | '/$lang/create'
    | '/$lang/'
    | '/$lang/lesson/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$lang/ar' | '/$lang/create' | '/$lang' | '/$lang/lesson/$id'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/ar'
    | '/$lang/create'
    | '/$lang/'
    | '/$lang/lesson/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/create': {
      id: '/$lang/create'
      path: '/create'
      fullPath: '/$lang/create'
      preLoaderRoute: typeof LangCreateRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/ar': {
      id: '/$lang/ar'
      path: '/ar'
      fullPath: '/$lang/ar'
      preLoaderRoute: typeof LangArRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/lesson/$id': {
      id: '/$lang/lesson/$id'
      path: '/lesson/$id'
      fullPath: '/$lang/lesson/$id'
      preLoaderRoute: typeof LangLessonIdRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangArRoute: typeof LangArRoute
  LangCreateRoute: typeof LangCreateRoute
  LangIndexRoute: typeof LangIndexRoute
  LangLessonIdRoute: typeof LangLessonIdRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangArRoute: LangArRoute,
  LangCreateRoute: LangCreateRoute,
  LangIndexRoute: LangIndexRoute,
  LangLessonIdRoute: LangLessonIdRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
